### ISSUE TITLE
Python 3.10 support

### ISSUE THREAD

**Issue by Squeemos** [ashutosh1919/explainable-cnn#7]
So it doesn't look like this project has python 3.10 support.

Ex:
```
from explainable_cnn import CNNExplainer

ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\bvano\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
```

Granted this fix is as easy as downgrading python, but then this doesn't support >=3.6

**Comment by BANADDA** [comment]
I got the same error, did you find a solution?

**Comment by ashutosh1919** [comment]
@Squeemos Do you want to raise PR to resolve this issue? Contributions are welcome

**Comment by Squeemos** [comment]
Sure. The fix is easy enough if you want to make the change as well, I'm okay with either.

**Comment by ashutosh1919** [comment]
@Squeemos please raise PR.

**Comment by Squeemos** [comment]
Gone ahead and done that [here](https://github.com/ashutosh1919/explainable-cnn/pull/8).
